---
- name: Configure Leafs
  hosts: leafs-l2evpn-mh
  gather_facts: no
  roles:
  - l2evpn_mh_leaf

- name: Configure DCGWs
  hosts: dcgws
  gather_facts: no
  roles:
  - l2evpn-mh_dcgw

- name: Configure RR
  hosts: rrs
  gather_facts: no
  roles:
  - l2evpn_rr
