interfaces:
  - name: ethernet-1/1
    index: 0
    ipv4_address_prefix: 21.1.1.1/31
  - name: ethernet-1/11
    index: 0
    ipv4_address_prefix: 11.1.1.0/31
  - name: ethernet-1/12
    index: 0
    ipv4_address_prefix: 11.1.2.0/31
  - name: ethernet-1/13
    index: 0
    ipv4_address_prefix: 11.1.3.0/31
  - name: ethernet-1/14
    index: 0
    ipv4_address_prefix: 11.1.4.0/31
  - name: lo0
    index: 0
    ipv4_address_prefix: 100.1.1.1/32

routing_policy:
     prefix_set_name: loopbacks
     policy_name: export-loopbacks

prefix_ip:
  - prefix_set_ip: 100.0.0.0/8
  - prefix_set_ip: 101.0.0.0/8

bgp:
  local_as: 65010
  router_id: 100.1.1.1

bgp_peer_groups:
  - peer_group : leafs
  - peer_group : dcgws

bgp_neighbors:
  - neighbor_ip : 11.1.1.1
    peer_group : leafs
    remote_as: 65011
  - neighbor_ip : 11.1.2.1
    peer_group : leafs
    remote_as: 65012
  - neighbor_ip : 11.1.3.1
    peer_group : leafs
    remote_as: 65013
  - neighbor_ip : 11.1.4.1
    peer_group : leafs
    remote_as: 65014
  - neighbor_ip : 21.1.1.0 
    peer_group : dcgws
    remote_as: 65001
