interfaces:
  - name: ethernet-1/1
    index: 0
    ipv4_address_prefix: 22.1.1.1/31
  - name: ethernet-1/11
    index: 0
    ipv4_address_prefix: 12.1.1.0/31
  - name: ethernet-1/12
    index: 0
    ipv4_address_prefix: 12.1.2.0/31
  - name: ethernet-1/13
    index: 0
    ipv4_address_prefix: 12.1.3.0/31
  - name: ethernet-1/14
    index: 0
    ipv4_address_prefix: 12.1.4.0/31
  - name: lo0
    index: 0
    ipv4_address_prefix: 100.2.1.1/32

routing_policy:
     prefix_set_name: loopbacks
     policy_name: export-loopbacks

prefix_ip:
  - prefix_set_ip: 100.0.0.0/8
  - prefix_set_ip: 101.0.0.0/8

bgp:
  local_as: 65020
  router_id: 100.2.1.1

bgp_peer_groups:
  - peer_group : leafs
  - peer_group : dcgws


bgp_neighbors:
  - neighbor_ip : 12.1.1.1
    peer_group : leafs
    remote_as: 65021
  - neighbor_ip : 12.1.2.1
    peer_group : leafs
    remote_as: 65022
  - neighbor_ip : 12.1.3.1
    peer_group : leafs
    remote_as: 65023
  - neighbor_ip : 12.1.4.1
    peer_group : leafs
    remote_as: 65024
  - neighbor_ip : 22.1.1.0
    peer_group : dcgws
    remote_as: 65002
