interfaces:
  - name: ethernet-1/1
    index: 0
    ipv4_address_prefix: 192.168.11.0/31
  - name: ethernet-1/2
    index: 0
    ipv4_address_prefix: 192.168.21.0/31
  - name: lo0
    index: 0
    ipv4_address_prefix: 100.0.0.1/32

routing_policy:
     prefix_set_name: loopbacks
     policy_name: export-loopbacks

prefix_ip:
  - prefix_set_ip: 100.0.0.0/8
  - prefix_set_ip: 101.0.0.0/8

bgp:
  local_as: 65000
  router_id: 100.0.0.1

bgp_peer_groups:
  - peer_group : dcgws

bgp_neighbors:
  - neighbor_ip : 192.168.11.1
    peer_group : dcgws
    remote_as: 65001
  - neighbor_ip : 192.168.21.1
    peer_group : dcgws
    remote_as: 65002
