---
- include_vars:
    file: "{{role_path}}/vars/{{inventory_hostname}}.yml"

- name: Configure Underlay DC Configs for {{inventory_hostname}}
  uri:
        url: http://{{ansible_host}}:80/jsonrpc
        user: admin
        password: NokiaSrl1!
        method: POST
        body: "{{ lookup('template', 'dc_jsonrpc.j2') }}"
        force_basic_auth: yes
        body_format: json
