---
- name: Configure Leafs
  hosts: leafs-l2evpn
  gather_facts: no
  roles:
  - l2evpn_leaf

- name: Configure DCGWs
  hosts: dcgws
  gather_facts: no
  roles:
  - l2evpn_dcgw

- name: Configure RR
  hosts: rrs
  gather_facts: no
  roles:
  - l2evpn_rr
