---
- name: Configure Leaves
  hosts: leafs-l3evpn
  gather_facts: no
  roles:
  - l3evpn_leaf

- name: Configure DCGWs
  hosts: dcgws
  gather_facts: no
  roles:
  - l3evpn-sh_dcgw
 
- name: Configure RRs
  hosts: rrs
  gather_facts: no
  roles:
  - l3evpn_rr

